"""session_bonus_percentile

Revision ID: 169033e975d2
Revises: 506b6085ab7e
Create Date: 2025-07-13 21:56:51.125210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "169033e975d2"
down_revision: Union[str, Sequence[str], None] = "506b6085ab7e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "quiz_sessions",
        sa.Column("bonus_points", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "quiz_sessions",
        sa.Column("percentile", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_index(
        op.f("ix_quiz_sessions_finished_at"),
        "quiz_sessions",
        ["finished_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_quiz_sessions_finished_at"), table_name="quiz_sessions")
    op.drop_column("quiz_sessions", "percentile")
    op.drop_column("quiz_sessions", "bonus_points")
    # ### end Alembic commands ###
