"""quiz

Revision ID: 958d0b20d294
Revises: 
Create Date: 2025-07-07 22:45:59.607486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958d0b20d294'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quizzes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('questions',
    sa.Column('type', sa.Enum('SINGLE_CHOICE', 'MULTI_CHOICE', 'FILL_GAP', 'MATCHING', name='questiontype'), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_quiz_id'), 'questions', ['quiz_id'], unique=False)
    op.create_table('quiz_sessions',
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('questions_count', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_sessions_quiz_id'), 'quiz_sessions', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_sessions_user_id'), 'quiz_sessions', ['user_id'], unique=False)
    op.create_table('quiz_title_translations',
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('quiz_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quiz_title_translations_quiz_id'), 'quiz_title_translations', ['quiz_id'], unique=False)
    op.create_table('options',
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('is_left', sa.Boolean(), nullable=True),
    sa.Column('is_right', sa.Boolean(), nullable=True),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_options_question_id'), 'options', ['question_id'], unique=False)
    op.create_table('question_translations',
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_translations_question_id'), 'question_translations', ['question_id'], unique=False)
    op.create_table('matching_option_correct_pairs',
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('left_option_id', sa.UUID(), nullable=False),
    sa.Column('right_option_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['left_option_id'], ['options.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['right_option_id'], ['options.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matching_option_correct_pairs_left_option_id'), 'matching_option_correct_pairs', ['left_option_id'], unique=False)
    op.create_index(op.f('ix_matching_option_correct_pairs_question_id'), 'matching_option_correct_pairs', ['question_id'], unique=False)
    op.create_index(op.f('ix_matching_option_correct_pairs_right_option_id'), 'matching_option_correct_pairs', ['right_option_id'], unique=False)
    op.create_table('option_translations',
    sa.Column('language', sa.String(length=5), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('option_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['options.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_option_translations_option_id'), 'option_translations', ['option_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_option_translations_option_id'), table_name='option_translations')
    op.drop_table('option_translations')
    op.drop_index(op.f('ix_matching_option_correct_pairs_right_option_id'), table_name='matching_option_correct_pairs')
    op.drop_index(op.f('ix_matching_option_correct_pairs_question_id'), table_name='matching_option_correct_pairs')
    op.drop_index(op.f('ix_matching_option_correct_pairs_left_option_id'), table_name='matching_option_correct_pairs')
    op.drop_table('matching_option_correct_pairs')
    op.drop_index(op.f('ix_question_translations_question_id'), table_name='question_translations')
    op.drop_table('question_translations')
    op.drop_index(op.f('ix_options_question_id'), table_name='options')
    op.drop_table('options')
    op.drop_index(op.f('ix_quiz_title_translations_quiz_id'), table_name='quiz_title_translations')
    op.drop_table('quiz_title_translations')
    op.drop_index(op.f('ix_quiz_sessions_user_id'), table_name='quiz_sessions')
    op.drop_index(op.f('ix_quiz_sessions_quiz_id'), table_name='quiz_sessions')
    op.drop_table('quiz_sessions')
    op.drop_index(op.f('ix_questions_quiz_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_table('quizzes')
    # ### end Alembic commands ###
