version: "3.9"

services:
  quiz_backend:
    container_name: quiz_backend
    restart: always
    build:
      context: ..
      dockerfile: build/Dockerfile
    entrypoint: /entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - ../environments/.env.local
    depends_on:
      - quiz_db
    networks:
      - zimran_network

  quiz_db:
    container_name: quiz_db
    restart: always
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - zimran_network

  quiz_redis:
    container_name: quiz_redis
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/postgresql/data
    networks:
      - zimran_network

  taskiq_worker:
    container_name: taskiq_worker
    build:
      context: ..
      dockerfile: build/Dockerfile
    restart: always
    env_file:
      - ../environments/.env.local
    entrypoint: uv run taskiq worker background_tasks.taskiq:broker
    networks:
      - zimran_network

  taskiq_scheduler:
    container_name: taskiq_scheduler
    build:
      context: ..
      dockerfile: build/Dockerfile
    restart: always
    env_file:
      - ../environments/.env.local
    entrypoint: uv run taskiq scheduler background_tasks.taskiq:scheduler
    networks:
      - zimran_network

volumes:
  pgdata:
  redis_data:

networks:
  zimran_network: