version: "3.9"

services:
  quiz_backend:
    container_name: quiz_backend
    restart: always
    build:
      context: ..
      dockerfile: build/Dockerfile
    entrypoint: /entrypoint.sh
    ports:
      - "8000:8000"
    env_file:
      - ../environments/.env.local
    depends_on:
      - quiz_db
    networks:
      - zimran_network

  quiz_db:
    container_name: quiz_db
    restart: always
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - zimran_network

  quiz_redis:
    container_name: quiz_redis
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/var/lib/postgresql/data
    networks:
      - zimran_network

  quiz_taskiq_worker:
    container_name: quiz_taskiq_worker
    build:
      context: ..
      dockerfile: build/Dockerfile
    restart: always
    env_file:
      - ../environments/.env.local
    entrypoint: uv run taskiq worker background_tasks.taskiq:broker
    networks:
      - zimran_network

  quiz_taskiq_scheduler:
    container_name: quiz_taskiq_scheduler
    build:
      context: ..
      dockerfile: build/Dockerfile
    restart: always
    env_file:
      - ../environments/.env.local
    entrypoint: uv run taskiq scheduler background_tasks.taskiq:scheduler
    networks:
      - zimran_network

  loki:
    image: grafana/loki:2.9.1
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/tmp/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - zimran_network

  promtail:
    image: grafana/promtail:2.9.1
    container_name: promtail
    volumes:
      - ../monitoring/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - zimran_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - zimran_network

volumes:
  pgdata:
  redis_data:
  loki_data:
  grafana_data:

networks:
  zimran_network: